// "use client"
import { useContext } from 'react'
import Footer from '../Components/Footer'
import Navbar from '../Components/Navbar'
import ThemeProvider, { ThemeContext } from './context/ThemeContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
        </ThemeProvider>
    </html>
  )
}
